name: build
on:
  push:
    branched:
      - develop
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-18.04
    outputs:
      proj: ${{ steps.set-proj.outputs.proj }}
      target: ${{ steps.set-target.outputs.target }}
    steps:
      - id: set-proj
        run: |
          echo '::set-output name=proj::["nfd","ndn-tools"]'
      - id: set-target
        run: |
          echo '::set-output name=target::["bionic-amd64","buster-amd64"]'
  ndn-cxx:
    needs: [prepare-matrix]
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target:
          - ${{ fromJson(needs.prepare-matrix.outputs.target) }}
      fail-fast: false
    name: ndn-cxx ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - run: bash build.sh ndn-cxx ${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: ndn-cxx ${{ matrix.target }}
          path: output
  proj:
    runs-on: ubuntu-18.04
    needs: [prepare-matrix, ndn-cxx]
    strategy:
      matrix:
        proj:
          - ${{ fromJson(needs.prepare-matrix.outputs.proj) }}
        target:
          - ${{ fromJson(needs.prepare-matrix.outputs.target) }}
      fail-fast: false
    name: ${{ matrix.proj }} ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ndn-cxx ${{ matrix.target }}
          path: deps
      - run: bash build.sh ${{ matrix.proj }} ${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.proj }} ${{ matrix.target }}
          path: output
