name: build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: bionic-amd64
            image: ubuntu:18.04
          - name: buster-amd64
            image: debian:buster
          - name: buster-armv7
            image: balenalib/generic-armv7ahf:buster-build
      fail-fast: false
    name: ${{ matrix.image }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: bash build.sh ${{ matrix.image }}
      - run: tar cJf deb.txz -C $HOME/output .
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: deb.txz
