name: build
on:
  push:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  ndn-cxx:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target:
          - bionic-amd64
          - buster-amd64
          - buster-armv7
          - buster-armv6
      fail-fast: false
    name: ndn-cxx ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - run: bash build.sh ndn-cxx ${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: ndn-cxx ${{ matrix.target }}
          path: output.txz
  proj:
    runs-on: ubuntu-18.04
    needs: ndn-cxx
    strategy:
      matrix:
        proj:
          - nfd
          - ndn-tools
        target:
          - bionic-amd64
          - buster-amd64
          - buster-armv7
          - buster-armv6
      fail-fast: false
    name: ${{ matrix.proj }} ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ndn-cxx ${{ matrix.target }}
      - run: bash build.sh ${{ matrix.proj }} ${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.proj }} ${{ matrix.target }}
          path: output.txz
